doc: add meeting minutes
nodejs/performance pull request #31
Opened 2022-11-30 09:59 UTC by sheplu

closes #28

2022-11-30 13:38 UTC, anonrig requested changes

2022-11-30 13:38 UTC, anonrig commented on meetings/2022-11-28.md
> +* Yagiz: better version of array-join - could be nice to check  https://github.com/anonrig/fast-array-join
```suggestion
* Yagiz: Open sourced @BridgeAR's faster version of array-join - could be nice to check  https://github.com/anonrig/fast-array-join
```

2022-11-30 13:38 UTC, anonrig commented on meetings/2022-11-28.md
> +* Atomic condition variable [#5](https://github.com/nodejs/performance/issues/5)
```suggestion
* Atomic condition variable [#5](https://github.com/nodejs/performance/issues/5)
  * removing agenda label due to missing benchmarks
```

2022-11-30 13:38 UTC, anonrig commented on meetings/2022-11-28.md
> +	* to be closed
```suggestion
	* Tony did a fantastic job, but unfortunately there isn't any room for improvement at the moment.
```

2022-11-30 13:38 UTC, anonrig commented on meetings/2022-11-28.md
> +	* nothing new
```suggestion
	* nothing new, moving to the next meetings agenda
```

2022-11-30 13:38 UTC, anonrig commented on meetings/2022-11-28.md
> +	* Yagiz: find more information and update the PR
```suggestion
	* Juan & Yagiz: find more information and come up with a PR
```

2022-11-30 13:38 UTC, anonrig commented on meetings/2022-11-28.md
> +* **GitHub Issue**: $GITHUB_ISSUE$
```suggestion
* **GitHub Issue**: https://github.com/nodejs/performance/issues/28
```

2022-11-30 13:38 UTC, anonrig commented on meetings/2022-11-28.md
> +
Stephen is missing from this list afaik

2022-11-30 17:57 UTC, anonrig approved these changes

2022-12-02 14:53 UTC, UlisesGascon approved these changes

2022-12-02 14:59 UTC, merged